FROM ubuntu:22.04

RUN wget https://github.com/caddyserver/xcaddy/releases/download/v0.3.5/xcaddy_0.3.5_linux_amd64.deb &&
    dpkg -i xcaddy_0.3.5_linux_amd64.deb &&
    rm xcaddy_0.3.5_linux_amd64.deb