name: Build tinygo

on:
  workflow_dispatch:
    inputs:
      tinygo_version:
        type: string
        required: false
        default: "0.29.0"
        description: "The version (e.g. 0.29.0) of TinyGo to install"
      tag:
        type: string
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install tinygo
        run: |
          curl https://github.com/tinygo-org/tinygo/releases/download/v0.29.0/tinygo_0.29.0_amd64.deb -L --output tinygo_0.29.0_amd64.deb && \
          sudo dpkg -i tinygo_0.29.0_amd64.deb && \
          rm tinygo_0.29.0_amd64.deb
      - name: Build
        working-directory: ./examples/tinygo
        run: tinygo build -o tinygo.wasm -target wasi
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.tag }}
          files: examples/tinygo/tinygo.wasm
