name: Build tinygo

on:
  workflow_dispatch:
    inputs:
      tinygo_version:
        type: string
        required: false
        default: "0.29.0"
        description: "The version (e.g. 0.29.0) of TinyGo to install"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install tinygo
        run: |
          curl https://github.com/tinygo-org/tinygo/releases/download/v${github.event.inputs.tinygo_version}/tinygo_${github.event.inputs.tinygo_version}_amd64.deb -L --output tinygo_${github.event.inputs.tinygo_version}_amd64.deb && \
          dpkg -i tinygo_${github.event.inputs.tinygo_version}_amd64.deb && \
          rm tinygo_${github.event.inputs.tinygo_version}_amd64.deb
      - name: Build
        run: |
          cd examples/tinygo
          tinygo build -o tinygo.wasm -target wasi
